### ISSUE TITLE
Project Meetings

### ISSUE THREAD

**Issue by Isinlor** [dke-group-23/DKE-Project#16]
# Period 1.2 Meetings

Group 23 (14:30) CG 2.002
--

**Comment by Isinlor** [comment]
@wenhao9 Could I ask you to write summaries from project meetings here? [The last one was perfect 👍 .]( https://github.com/dke-group-23/DKE-Project/issues/9#issuecomment-428192680)

**Comment by wenhao9** [comment]
Of course
