### ISSUE TITLE
Assiging the roles

### ISSUE THREAD

**Issue by Isinlor** [dke-group-23/DKE-Project#2]
Current status:

We have two presentation co-ordinators:
- Anna
- Wen

Therefore 3 product co-ordinators:
- Selim
- Pierre
- Sjors

And Tomek as project leader.

The rest of the issue...

There seem to be 4 roles to assign ([Appendix D Project groups, tutors and lecturers](https://github.com/dke-group-23/DKE-Project/blob/master/project%201-1.pdf)):

- [x] Project leader: 
- monitors the process / progress 
- updates the planning
- external communication
- responsible for handing in the report and product

- [x] Editor: 
- responsible for the report checks texts written by other team members 
- gives writing assignments 
- puts together the individual contributions resulting in a complete and coherent report 
- administer of the literature for the report 
 
- [x] Presentation co-ordinator: 
- responsible for the presentation
- tests the hardware used for the presentation
- ensures coherence of the sheets and slides 
 
- [x] Product co-ordinator: 
- assigns tasks with respect to the creation of the product 
- links the different modules of the product
- manages the documentation, manual(s), diagrams
- finishing touch
- monitors progress of the product according to the design

The role of editor won't be applicable in the first part of the project.

I would say for now we need:
- 1 project leader
- 2 presentation co-ordinators
- 3 product co-ordinators
 
As we agreed on the kick off meeting I can be a project leader. 

Other roles can be on first come, first serve basis or whatever else, just to get it done.

More important is splitting tasks related to the product.

Based on my experience working on algorithms is difficult in big groups, therefore:
- two people should be responsible for exact algorithm
- two people should be responsible for upper bound algorithm
- we need to figure out quick how difficult is doing the lower bound algorithm

In this issue please write down how good you are at programming / presenting and which tasks you would want to take. I.e.:
- presentation vs. product
- exact vs. upper algorithm

**Comment by Seeeeeyo** [comment]
I can be a product co-ordinator. 
I haven't looked at the problem yet so I don't really know yet which algorithm I should work on. 
I am a beginner at programming but I'd like to practice a lot to get experience and learn as much as possible.

**Comment by wenhao9** [comment]
I can be a presentation co-ordinator. I'm a bit of a loose gun. Can't program as like writing, but I have a good comprehension of it. Extraverted when needed, so I'm probably a good fit as a presentator or communicator

**Comment by ghost** [comment]
I can be a product co-ordinator since I have a math background and some prior programming experience. I'd be interested in doing the upper algorithm.

**Comment by Isinlor** [comment]
@Selimgilon Which
