### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by wenhao9** [dke-group-23/DKE-Project#21]
Hello, 

As I was assigned to think of a good and easy hint method I came up with the following ideas:

By clicking the hint buttons one of the following will happen:

1. The graph will fill up one random node/vertice. 

I think that is my best idea. 

If we can't agree on that one I have the following second-rate ideas:

- Show the number of colors needed to fill in the graph
- Let a node/vertice blink which is needed to be filled in with the already selected color
- Delete the part of the graph which is incorrect (so when the amount of colors is already exceeded)
- A sudden audio plays with Shia Lebeouf saying: JUST DO IT!!!

That was everything I could think of which wasn't already mentioned in our meetings.

I made a poll to vote which one is the best: 

https://linkto.run/p/TDKDNU72

Please let us know which one is your favorite, voting is unanimous.

With kind regards,

Wen

**Comment by Seeeeeyo** [comment]
Hi guys, 
Here are some ideas for hints. I am still working on it. 
[Hints ideas.docx](https://github.com/dke-group-23/DKE-Project/files/2669445/Hints.ideas.docx)
