### ISSUE TITLE
Tuesday meeting

### ISSUE THREAD

**Issue by Isinlor** [dke-group-23/DKE-Project#9]
We meet on Tuesday @Bouillonstraat 8-10 at 12:00. 

On 12:45 meeting with supervisor starts in room 2.002.

Agenda proposed by DKE:
1.	Opening
2.	Announcements 
a.	by the group members
b.	by the tutor
3.	Incoming/outgoing post or mail
4.	Minutes last meeting (mention date of meeting)
5.	State of the courses
6.	State of the project
a.	planning
b.	correction of the planning
c.	discussion on the log book
d.	discussion on the results of a brainstorm session or of a sub group
7.	Cooperation
8.	Appointments
a.	tasks to be done
b.	organization of the work
c.	chairman and secretary next meeting; monitoring the log book
9.	Any other business

**Comment by Isinlor** [comment]
Best case scenario for that meeting is that everyone would have understanding of some algorithm, so that she/he could explain it to the rest of us.

Then we can discuss them and decide on what algorithm we go for.

Bare in mind that we will need to start to code them after that meeting.

**Comment by Isinlor** [comment]
@wenhao9 It would be nice if you could summarize the meeting here.

**Comment by wenhao9** [comment]
Hello everyone,

Here's the summary of the meeting om Tuesday:

We discussed the fact that we already cleared some objectives: We communicate via Github, we assigned the roles and diversication of the work (upper bound, exact bound, lower bound). There will be no report, so there will be no editor. We already made some deadlines for ourselves in the chart which Tomasz made.

The guy we spoke to gave us the following tips and information on the following topics:

General
- We better start now and don't procrastinate; better finish early than late no?

The Programming:
- We should make at least 1 of the bounds, even if it doesn't work out.
- The deadline to hand in our code is Friday morning

The Presentation:
-  Pietro & Efgheni (something like that) will be judging us
- Everyone needs to say something during the presentation, some can say more than others, but try to keep it balanced
- Try to be a little bit specific (so not general, but not too specific either)
- No jokes or limit the amount of jokes
- The simpler the better
- No effects or fancy stuff
- Be precise and simple
- have more pictures than text
- max 10-12 slides
- Be ready to answer WHY we use certain methods

The structure of the presentation is as follows:
- Project Description
- Stating your sources 
- Experiment (no proofs)
* Use graphs
* try implementing a video here of the in- and output
- Result
- Conclusion
- Plan for next week

Which Skills are tested:
1. Analyzing: Analytics: Knowing why you use a certain method
2. Cohesion in the group
3. Understanding of the topic
4. Fabulousness and Italian cuisine
5. What you learned in this block basically

That's it!

Let me know if I forgot something.

Wen
